name: notustohtml
description: Convert the Notus document format to an HTML representation.
version: 0.1.3
homepage: https://github.com/JacobWrenn/notustohtml

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  notus:
    git:
      url: https://github.com/lucygeneric/notus.git
      ref: c434dc6
  quill_delta:
    git:
      url: https://github.com/lucygeneric/quill-delta-dart/
  html: ^0.15.0

dev_dependencies:
  test:
