name: notustohtml
description: Convert the Notus document format to an HTML representation.
version: 0.1.0
homepage: https://github.com/JacobWrenn/notustohtml

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  notus: ^1.0.0-dev.8.0
  quill_delta: ^3.0.0-nullsafety.0
  html: ^0.15.0

dev_dependencies:
  test:
